public_uhc_teamspeak_auth:
    resource: "@PublicUHCTeamspeakAuthBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
