# routes.yml
authcheck:
    path:     /auth
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\TeamspeakAuthController::authAction' }

ts3code:
    path:     /teamspeakcode
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\TeamspeakAuthController::requestTeamspeakAction' }

homepage:
    path:     /
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\TeamspeakAuthController::indexAction' }
