# 'API' like routes that return JSON for the front end
authcheck:
    path:     /auth
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::authAction' }

teamspeakcode:
    path:     /teamspeakcode
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::requestTeamspeakAction' }

avatarhelm:
    path:     /skins/helm/{username}/{size}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\SkinController::helmAction', size: 16 }

avatarskin:
    path:     /skins/skin/{username}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\SkinController::skinAction', size: 16 }

avatarhead:
    path:     /skins/head/{username}/{size}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\SkinController::headAction', size: 16 }

# Standard front end pages

homepage:
    path:     /
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::indexAction' }

teamspeakrequest:
    path:     /teamspeakrequest
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::teamspeakRequestPageAction' }

verifyaccount:
    path:     /verifyaccount/{uuid}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::verifyAccountPageAction', uuid: ~ }
    requirements:
        uuid: .+

complete:
    path:     /complete/{mc_name}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::completeAction', mc_name: ~ }

# API pages

api_verified:
    path:     /api/verified
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\APIController::checkVerified', checkOnline: false }

api_online:
    path:     /api/online
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\APIController::checkVerified', checkOnline: true }


##############
# API Routes #
##############

api_v1_teamspeak_code:
    path:     /api/v1/teamspeakCodes/{username}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakCodeController::requestTeamspeakCodeAction', _format: json }
    methods: [GET]
    requirements: { username: .* }

api_v1_latest_authentications:
    path:     /api/v1/authentications/latest/{limit}/{offset}
    defaults:
        _controller: 'PublicUHC\TeamspeakAuth\Controllers\AuthenticationController::authenticationsAction'
        _format: json
        limit: 10
        offset: 0
    methods: [GET]
    requirements:
        limit: \d+
        offset: \d+

api_v1_authenticate:
    path:     /api/v1/authentications
    defaults:
        _controller: 'PublicUHC\TeamspeakAuth\Controllers\AuthenticationController::authenticateAction'
        _format: json
    methods: [POST]

# catchall to use JSON error for all routes at /api/.*
api_catchall:
    path:     /api/{anything}
    defaults: { _format: json }
    requirements:
        anything: .*