# 'API' like routes that return JSON for the front end
authcheck:
    path:     /auth
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::authAction' }

teamspeakcode:
    path:     /teamspeakcode
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::requestTeamspeakAction' }

latestauths:
    path:     /latest
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::latestAuthsAction' }

avatarhelm:
    path:     /skins/helm/{username}/{size}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\SkinController::helmAction', size: 16 }

avatarskin:
    path:     /skins/skin/{username}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\SkinController::skinAction', size: 16 }

avatarhead:
    path:     /skins/head/{username}/{size}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\SkinController::headAction', size: 16 }

# Standard front end pages

homepage:
    path:     /
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::indexAction' }

teamspeakrequest:
    path:     /teamspeakrequest
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::teamspeakRequestPageAction' }

verifyaccount:
    path:     /verifyaccount/{uuid}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::verifyAccountPageAction', uuid: ~ }
    requirements:
        uuid: .+

complete:
    path:     /complete/{mc_name}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::completeAction', mc_name: ~ }

# API pages

api_verified:
    path:     /api/verified/{mc_uuid}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\APIController::checkVerified', checkOnline: false }

api_online:
    path:     /api/online/{mc_uuid}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\APIController::checkVerified', checkOnline: true }