# 'API' like routes that return JSON for the front end
authcheck:
    path:     /auth
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::authAction' }

teamspeakcode:
    path:     /teamspeakcode
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::requestTeamspeakAction' }

# Standard front end pages

homepage:
    path:     /
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::indexAction' }

teamspeakrequest:
    path:     /teamspeakrequest
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::teamspeakRequestPageAction' }

verifyaccount:
    path:     /verifyaccount/{uuid}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::verifyAccountPageAction', uuid: ~ }
    requirements:
        uuid: .+

complete:
    path:     /complete/{mc_name}
    defaults: { _controller: 'PublicUHC\TeamspeakAuth\Controllers\TeamspeakAuthController::completeAction', mc_name: ~ }