# routes.yml
authcheck:
    path:     /auth
    defaults: { _controller: 'com\publicuhc\ts3auth\Ts3Auth::authAction' }

ts3code:
    path:     /ts3code
    defaults: { _controller: 'com\publicuhc\ts3auth\Ts3Auth::requestTeamspeakAction' }
