PublicUHC\Bundle\TeamspeakAuthBundle\Entity\TeamspeakAccount:
    exclusion_policy: ALL
    read_only: true
    properties:
        authentications:
            since_version: 1.0
            read_only: true
            type: array<PublicUHC\Bundle\TeamspeakAuthBundle\Entity\Authentication>
            expose: true